spring:
  application:
    name: High-Mountain

  jackson:
    default-property-inclusion: non_null

  profiles:
    active: secrets, aws

  config:
    import:
      - optional:file:./application-secrets.yml
      - optional:file:./application-aws.yml

  #aws:
#  s3:
#    bucket:
#      name: your-s3-bucket-name  # 민감하지 않은 S3 버킷 이름

  #  // test DB (DB ?? ? ?? ?? ??)
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

server:
  port: 8091

jwt:
  secret: ${JWT_SECRET}

